In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train.csv')[['Age', 'Pclass', 'Fare', 'Survived']]

In [3]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [4]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [5]:
X= df.drop(columns=['Survived'])
y = df['Survived']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
X_train.head()

      Age  Pclass     Fare
331  45.5       1  28.5000
733  23.0       2  13.0000
382  32.0       3   7.9250
704  26.0       3   7.8542
813   6.0       3  31.2750

In [14]:
knn = KNNImputer()
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [15]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

      Age  Pclass      Fare
0    45.5     1.0   28.5000
1    23.0     2.0   13.0000
2    32.0     3.0    7.9250
3    26.0     3.0    7.8542
4     6.0     3.0   31.2750
..    ...     ...       ...
707  21.0     3.0    7.6500
708  39.0     1.0   31.0000
709  41.0     3.0   14.1083
710  14.0     1.0  120.0000
711  21.0     1.0   77.2875

[712 rows x 3 columns]

In [16]:
lr = LogisticRegression()
lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.7430167597765364

In [18]:
# comparison with simple imputer --> mean
 
si = SimpleImputer()
 
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [19]:
pd.DataFrame(X_train_trf2,columns=X_train.columns)

           Age  Pclass      Fare
0    45.500000     1.0   28.5000
1    23.000000     2.0   13.0000
2    32.000000     3.0    7.9250
3    26.000000     3.0    7.8542
4     6.000000     3.0   31.2750
..         ...     ...       ...
707  21.000000     3.0    7.6500
708  29.498846     1.0   31.0000
709  41.000000     3.0   14.1083
710  14.000000     1.0  120.0000
711  21.000000     1.0   77.2875

[712 rows x 3 columns]

In [20]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)
y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_test,y_pred2)

0.7374301675977654

In [ ]:
# Here KNNImputer performed better than SimpleImputer with mean strategy.